# 服务端口
server:
  port: 8101

#### eureka 基本信息配置
eureka:
  instance:
    ### 注册到eureka api地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      ### 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    ### 表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false
    ### 表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false
